---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: 200
    outlierDetection:
      consecutive5xxErrors: 2
      consecutiveGatewayErrors: 2
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  subsets:
    - name: gold
      labels:
        version: gold
    - name: red
      labels:
        version: red
    - name: broken
      labels:
        version: broken
