---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews.default.svc.cluster.local
    - reviews.crispcam.com
  gateways:
    - mesh
    - asm-gateway/gateway
  http:
    - match:
        - headers:
            user-agent:
              regex: '.*Firefox/\d\d\d?.\d\d?$'
      route:
        - destination:
            host: reviews
            subset: red
          weight: 100
    - route:
        - destination:
            host: reviews
            subset: gold
          weight: 100